name: CI/CD to ECS Fargate
on:
  workflow_run:
    workflows: ["Run Unit Tasks"]
    branches: [main]
    types:
      - completed

env:
    AWS_REGION: ap-south-1
    ECR_REPOSITORY: documentportal
    ECR_SERVICE: document-portal-service
    ECR_CLUSTER: document-portal-cluster
    ECR_TASK_DEFINITION: .github/workflows/task_definition.json
    CONTAINER_NAME: document-portal-container

permissions:
    id-token: write
    contents: read

jobs:
    check_status:
        runs-on: ubuntu-latest
        if: github.event.workflow_run.conclusion == 'success'
        steps:
            - name: CI passed on main branch
              run: echo "CI passed on main branch, proceeding to build and deploy"

    build_and_push:
        name: Build and Push Docker Image
        needs: [check_status]
        runs-on: ubuntu-latest
        outputs:
            image: ${{ steps.build-image.outputs.image }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.workflow_run.head_sha }}

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: Build and Push Docker Image
              id: build-image
              env:
                ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                IMAGE_TAG: ${{ github.event.workflow_run.head_sha }}
              run: |
                echo "Building Docker image..."
                IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
                docker build -t $IMAGE_URI .
                echo "Pushing Docker image to ECR..."
                docker push $IMAGE_URI
                echo "image=$IMAGE_URI" >> $GITHUB_OUTPUT
                echo "DEBUG: IMAGE_URI IS -> $IMAGE_URI"

    deploy:
        name: Deploy to ECS Fargate
        needs: [build_and_push]
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v4
            with:
                ref: ${{ github.event.workflow_run.head_sha }}

          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v2
            with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.AWS_REGION }}

          - name: Render Task Definition
            id: render-task
            uses: aws-actions/amazon-ecs-render-task-definition@v1
            with:
                task-definition: ${{ env.ECR_TASK_DEFINITION }}
                container-name: ${{ env.CONTAINER_NAME }}
                image: ${{ needs.build_and_push.outputs.image }}

          - name: Deploy to ECS
            uses: aws-actions/amazon-ecs-deploy-task-definition@v1
            with:
                task-definition: ${{ steps.render-task.outputs.task-definition }}
                service: ${{ env.ECR_SERVICE }}
                cluster: ${{ env.ECR_CLUSTER }}
                wait-for-service-stability: true

          - name: Done!
            run: echo "Deployment to ECS Fargate completed successfully!"
